### ISSUE TITLE
How can I add this to the pipeline?

### ISSUE THREAD

**Issue by panwroblewski** [zenato/sbt-babel#10] opened 2018-02-21 16:23 UTC
How can I use it in this pipeline?
pipelineStages := Seq(rjs, gzip)

Also, where should I declare any input for the plugin? 
lazy val root = (project in file(".")).enablePlugins(SbtWeb) - is this the target folder declaration?

**Comment by zenato** [comment] 2018-02-22 00:05
Duplicate of #3 
Unfortunately, it is impossible.

**Closed as completed by zenato** 2018-02-22 00:05 UTC
Labels: duplicate
